### ISSUE TITLE
Query should support basic templates to inject date

### ISSUE THREAD

**Issue by timwis** [timwis/subscribeme#3]
Some APIs will let you query for "today's records" using something like `?where=date_created = CURRENT_DATE()`. Others, though, will require explicitly passing a date string, ie. `?where=date_created >= '2017-03-05'`. It seems like Socrata requires this too, so supporting this would be helpful to have a wide reach in the open data world.

I imagine the solution would be to allow services to have "templatized" queries, ie:

```
?where=date_created >= '{{dateFormat Date.now() "YYYY-MM-DD"}}'
```

**Comment by timwis** [comment]
@chrismetcalf may have advice on Socrata's APIs (and may generally be interested in this project too!)

**Comment by chrismetcalf** [comment]
👋 

Yup, with Socrata you'll need to pass in an actual date string with the query, we don't yet support a `CURRENTDATE()` function or macro.

Also, hell yes I'm interested in this project 😄

**Comment by timwis** [comment]
We'll also need this helper to parse a date string, so that you can do things like `{{ dateFormat 'today' 'YYYY-MM-DD' }}` or `today - 2` etc.

**Comment by timwis** [comment]
@davewalk @mjumbewu @themightychris any suggestions on the format for this? I feel like I'm overthinking it. The idea of parsing arbitrary strings like `today - 1` to get a date and then formatting that date seems overkill. I wish there were a familiar pattern we could implement.

**Comment by timwis** [comment]
This may be handy: https://github.com/samsonjs/strftime

**Comment by themightychris** [comment]
I love PHP's `strtotime` for this, but it may be overkill / too ambiguous.

On the simpler end of the spectrum I'd prefer to see `YYYY-MM-DD HH:II:SS` (space/punctuation ignored) and `now` as supported values

**Comment by timwis** [comment]
So we'll need to first parse a human-readable time string (like `today`, `yesterday`, `2 days ago`, etc.), then format the date. The latter is easy and common. The former is less common. For parsing, a simple library is [substack/parse-messy-time](https://github.com/substack/parse-messy-time). A more complex one is [wanasit/chrono](https://github.com/wanasit/chrono)
